Atualizando Setup Inicial
augustnmonteiro/gestor-de-encomendas pull request #12
Opened 2023-04-10 15:10 UTC by DavidFreitas0

2023-04-10 16:22 UTC, Luiz-Honorato approved these changes

2023-04-10 18:50 UTC, hugo3az approved these changes

2023-04-10 19:03 UTC, ValderlanioJ approved these changes

2023-04-10 19:47 UTC, ivinakarol approved these changes

2023-04-10 21:55 UTC, vanessarlrodrigues approved these changes

2023-04-10 23:21 UTC, augustnmonteiro requested changes
`AddOrder, changeOrdersStatus, listOrders, orderOrders, searchOrders` devem está no mesmo arquivo pois todas estão na mesma rota: `/order/`

No `main.js` devemos colocar o connection dentro de um *middleware* para que consigamos acessa-lo de dentro das rotas.

No `main.js` devemos importar as rotas

2023-04-10 23:32 UTC, augustnmonteiro commented
exemplo de `middleware` https://github.com/Luiz-Honorato/desafios/blob/main/react-server/backend/src/server.js#L23

2023-04-12 13:47 UTC, DavidFreitas0 commented on backend/routes/ordersRoutes.js
> +//ROUTER PARA ALTERAR STATUS DA ENCOMENDA (changeOrdersStatus)
Cada rota tem seu espaço para ser desenvolvido, o responsável pela rota, desenvolve a estrutura e funcionalidade dentro do espaço especifico para a sua rota.

2023-04-12 15:39 UTC, vanessarlrodrigues approved these changes

2023-04-12 15:53 UTC, Luiz-Honorato approved these changes

2023-04-12 17:00 UTC, hugo3az approved these changes

2023-04-12 17:02 UTC, ivinakarol approved these changes

2023-04-12 23:05 UTC, augustnmonteiro approved these changes

2023-04-12 23:05 UTC, merged