Adcionando estrutura frontend
augustnmonteiro/gestor-de-encomendas pull request #15
Opened 2023-04-14 02:26 UTC by Luiz-Honorato

Pessoal fiz algumas pastas contendo as rotas como foi indicado, em cada pasta contém arquivos de componentes, não criei todos os arquivos de componentes, e também fiz uma pasta de componentes, por hora contém apenas o Header.
Quem for trabalhar em uma rota específica se atentar para criar arquivos separados.  Além disso é necessário a instalação
do pacote react-rout-dom, utilizei a ultima versão.

2023-04-14 03:39 UTC, vanessarlrodrigues approved these changes

2023-04-14 23:03 UTC, DavidFreitas0 approved these changes

2023-04-14 23:18 UTC, augustnmonteiro requested changes

2023-04-14 23:18 UTC, augustnmonteiro commented on README.md
> +Luiz Roberto git Luiz-Honorato
essa linha está duplicada

2023-04-14 23:18 UTC, augustnmonteiro commented on frontend/src/App.js
> +        </Routes>
Podemos usar somente um componente `<Routes>` e colocar todas as rotas dentro dele:
ex:
```
       <Routes>
          <Route path="/" element={<Home/>}/>
          <Route path="/cadastro" element={<Form/>}/>
          <Route path="/list" element={<List/>}/>
        </Routes>
```

2023-04-14 23:18 UTC, augustnmonteiro commented on frontend/src/App.js
> +import Form from "./pages/form/Form";
ao invês de chamar de `Form` podemos chamar de `AddPackage` ou `AddOrder` ou ...

2023-04-14 23:18 UTC, augustnmonteiro commented on frontend/src/App.js
> +import List from "./pages/List/List";
colocar nome mais descritivo no Componente

2023-04-14 23:18 UTC, augustnmonteiro commented on frontend/src/components/header/Nav.js
> +                        <Link to="/cadastro">Cadastro</Link>
tentar usar uma rota `/cadastro` mais descritiva ex: `/packages/add`

2023-04-14 23:18 UTC, augustnmonteiro commented on frontend/src/pages/form/Form.module.css
esse arquivo é necessario?

2023-04-14 23:18 UTC, augustnmonteiro commented on frontend/src/pages/home/Home.module.css
esse arquivo é necessario?

2023-04-16 15:28 UTC, DavidFreitas0 approved these changes

2023-04-16 15:57 UTC, ivinakarol approved these changes

2023-04-17 11:51 UTC, DavidFreitas0 approved these changes

2023-04-17 14:56 UTC, vanessarlrodrigues approved these changes

2023-04-17 18:31 UTC, closed without merging