Route para alterar o status
augustnmonteiro/gestor-de-encomendas pull request #20
Opened 2023-04-18 14:05 UTC by vanessarlrodrigues

2023-04-18 14:08 UTC, hugo3az approved these changes

2023-04-18 14:13 UTC, ivinakarol approved these changes

2023-04-19 12:19 UTC, ValderlanioJ approved these changes

2023-04-19 23:22 UTC, augustnmonteiro requested changes

2023-04-19 23:22 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +    }
não podemos usar o PUT /:id para atualizar somente o status, pois o PUT /:id é usado para atualizar todos os campos editaveis. 
criar uma nova rota para mudar o status

2023-04-19 23:29 UTC, closed without merging