adicionando o backend dos indicadores
augustnmonteiro/gestor-de-encomendas pull request #21
Opened 2023-04-18 14:09 UTC by ivinakarol

2023-04-18 14:25 UTC, DavidFreitas0 approved these changes

2023-04-19 18:05 UTC, ValderlanioJ approved these changes

2023-04-19 23:15 UTC, augustnmonteiro requested changes

2023-04-19 23:15 UTC, augustnmonteiro commented on backend/src/routes/indicatorsRoutes.js
> +    }
o indicadores não precisa levar checar se foi deletado

2023-04-19 23:15 UTC, augustnmonteiro commented on backend/src/routes/indicatorsRoutes.js
> +  }
o indicadores não precisa levar checar se foi deletado

2023-04-19 23:15 UTC, augustnmonteiro commented on backend/src/routes/indicatorsRoutes.js
> +    }
o indicadores não precisa levar checar se foi deletado

2023-04-19 23:15 UTC, augustnmonteiro commented on backend/src/routes/indicatorsRoutes.js
> +router.get('/sum', (req, res) => {
`/total-weight` ou `/sum-weight` ou `weight`

2023-04-19 23:15 UTC, augustnmonteiro commented on backend/src/routes/indicatorsRoutes.js
> +router.get('/count', (req, res) => {
`count-orders` or `total-orders` or `orders`

2023-04-19 23:15 UTC, augustnmonteiro commented on backend/src/routes/indicatorsRoutes.js
> +router.get('/groupBy', (req, res) => {
`total-orders-by-status` or `orders-by-status`

2023-04-19 23:15 UTC, augustnmonteiro commented on backend/src/routes/indicatorsRoutes.js
> +  let query = "SELECT status, count(id) as number_status FROM orders GROUP BY status";
trocar o `number_status` por `total`

2023-04-20 11:36 UTC, closed without merging