Adicionando rota de Ordenar Encomendas - Backend
augustnmonteiro/gestor-de-encomendas pull request #22
Opened 2023-04-19 22:50 UTC by DavidFreitas0

Rota para Ordenar Encomendas por nome Asc e Desc.

2023-04-19 23:03 UTC, ivinakarol approved these changes

2023-04-19 23:06 UTC, augustnmonteiro requested changes
usar a mesma rota do `/list` e adicionar parametro para fazer o controle da ordem

2023-04-20 23:22 UTC, augustnmonteiro requested changes

2023-04-20 23:22 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +        }
a ordem não pode estar dependente do `showDeleted`

2023-04-20 23:22 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +router.get('/:order', (req, res) => {
usar query string ex: `?order=asc`

2023-04-21 17:58 UTC, ValderlanioJ approved these changes

2023-04-21 23:12 UTC, augustnmonteiro approved these changes

2023-04-22 09:48 UTC, Luiz-Honorato approved these changes

2023-04-22 10:45 UTC, hugo3az approved these changes

2023-04-22 14:44 UTC, merged