Task alterar status completa
augustnmonteiro/gestor-de-encomendas pull request #25
Opened 2023-04-20 02:23 UTC by vanessarlrodrigues

2023-04-20 02:26 UTC, hugo3az approved these changes

2023-04-20 14:22 UTC, augustnmonteiro requested changes

2023-04-20 14:22 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +        let newstatus = req.body.status;
* o newStatus pode ser uma constante já que ele não muda
* também podemos criar essa constante antes do if e usar ela no if

2023-04-20 23:18 UTC, augustnmonteiro requested changes

2023-04-20 23:18 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +    const newStatus = req.body.status;
não precisa do `/put`

2023-04-21 17:59 UTC, ValderlanioJ approved these changes

2023-04-21 23:11 UTC, augustnmonteiro requested changes

2023-04-21 23:11 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +    if (newStatus == "AGUARDANDO_ENVIO" || newStatus == "SAIU_PARA_ENTREGA" || newStatus == "ENTREGUE") {
mudar status para inglês conforme o Pull Request do Luiz #27

2023-04-21 23:50 UTC, augustnmonteiro approved these changes

2023-04-21 23:51 UTC, DavidFreitas0 approved these changes

2023-04-21 23:52 UTC, merged