Update back indicadores
augustnmonteiro/gestor-de-encomendas pull request #26
Opened 2023-04-20 11:44 UTC by ivinakarol

2023-04-20 18:28 UTC, augustnmonteiro requested changes

2023-04-20 18:28 UTC, augustnmonteiro commented on backend/src/routes/indicatorsRoutes.js
> +    let query = "SELECT SUM(weight) as total FROM orders";
como o `query` não muda, pode ser uma constante

2023-04-20 18:28 UTC, augustnmonteiro commented on backend/src/routes/indicatorsRoutes.js
> +  let query = "SELECT COUNT(id) as total FROM orders";
como o `query` não muda, pode ser uma constante

2023-04-20 18:28 UTC, augustnmonteiro commented on backend/src/routes/indicatorsRoutes.js
> +  let query = "SELECT status, count(id) as total FROM orders GROUP BY status";
como o `query` não muda, pode ser uma constante

2023-04-20 23:56 UTC, DavidFreitas0 approved these changes

2023-04-21 23:10 UTC, augustnmonteiro approved these changes

2023-04-21 23:15 UTC, ValderlanioJ approved these changes

2023-04-22 09:50 UTC, Luiz-Honorato approved these changes

2023-04-22 10:44 UTC, hugo3az approved these changes

2023-04-24 17:24 UTC, merged