adcionando rota add
augustnmonteiro/gestor-de-encomendas pull request #27
Opened 2023-04-20 17:49 UTC by Luiz-Honorato

2023-04-20 18:31 UTC, augustnmonteiro requested changes

2023-04-20 18:31 UTC, augustnmonteiro commented on backend/src/main.js
> +app.use('/order', ordersRouter);
assim todas as rotas que servem para `/orders` também vão servir para `/order`

2023-04-20 18:31 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +router.post('/add', (req, res) => {
não precisa do `/add` o metodo post já é para add

2023-04-20 18:31 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +        (status === "Aguardando" || status === "Saiu para entrega" || status === "Entregue")) {
os status como são constantes, podemos colocar eles `AGUARDANDO` `SAIU_PARA_ENTREGA` `ENTREGUE`

2023-04-20 18:31 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +        (status === "Aguardando" || status === "Saiu para entrega" || status === "Entregue")) {
e seria melhor colocar em inglês, o frontend tem que tratar o dado para mostrar pro usuario de qualquer forma

2023-04-21 18:00 UTC, ValderlanioJ approved these changes

2023-04-21 23:10 UTC, augustnmonteiro approved these changes

2023-04-22 10:43 UTC, hugo3az approved these changes

2023-04-22 14:47 UTC, DavidFreitas0 approved these changes

2023-04-23 13:15 UTC, merged