adicionando rota de pesquisa pelo banco
augustnmonteiro/gestor-de-encomendas pull request #29
Opened 2023-04-20 20:19 UTC by hugo3az

2023-04-20 23:12 UTC, augustnmonteiro requested changes

2023-04-20 23:12 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +router.get('/list/:type/:busca', (req, res) => {
tirar o `/list`. usar query string para `type` e para `busca`

2023-04-20 23:12 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +    let sql = `SELECT * FROM orders WHERE ${req.params.type} like '%${req.params.busca}%' AND  deleted_at IS NULL`
checar se o `type` é pesquisavel

2023-04-21 23:17 UTC, ValderlanioJ approved these changes

2023-04-22 12:39 UTC, closed without merging