formulário para adcionar encomenda
augustnmonteiro/gestor-de-encomendas pull request #35
Opened 2023-05-10 18:39 UTC by Luiz-Honorato

2023-05-10 23:44 UTC, augustnmonteiro requested changes

2023-05-10 23:44 UTC, augustnmonteiro commented on frontend/src/pages/add-order/AddOrder.js
> +    function unitMeasurement(unit, value) {
mudar o nome da função para descrever melhor

2023-05-10 23:44 UTC, augustnmonteiro commented on frontend/src/pages/add-order/AddOrder.js
> +        }
não precisa do else

2023-05-10 23:44 UTC, augustnmonteiro commented on frontend/src/pages/add-order/AddOrder.js
> +        }
não precisa do else

2023-05-10 23:44 UTC, augustnmonteiro commented on frontend/src/pages/add-order/AddOrder.js
> +                return res
esse return não vai ser o return da função `registerAnOrder` porque as promises são executadas de forma assincronas.

2023-05-10 23:44 UTC, augustnmonteiro commented on frontend/src/pages/add-order/AddOrder.js
> +            fetch(url, {
usar a função do request, como no pull request #33

2023-05-10 23:44 UTC, augustnmonteiro commented on frontend/src/pages/add-order/AddOrder.js
> +        }
não precisa do else

2023-05-17 15:50 UTC, augustnmonteiro approved these changes

2023-05-17 23:01 UTC, ivinakarol approved these changes

2023-05-17 23:03 UTC, DavidFreitas0 approved these changes

2023-05-17 23:04 UTC, hugo3az approved these changes

2023-05-17 23:35 UTC, merged