Add task para alteração de status
augustnmonteiro/gestor-de-encomendas pull request #36
Opened 2023-05-15 23:09 UTC by vanessarlrodrigues

2023-05-15 23:35 UTC, augustnmonteiro requested changes

2023-05-15 23:35 UTC, augustnmonteiro commented on .vscode/launch.json
> +    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
remover comentario, fica um json invalido

2023-05-15 23:35 UTC, augustnmonteiro commented on backend/src/routes/ordersRoutes.js
> +        res.status(400).send(error);
enviar um json dizendo que está bad request, `{status: 400}`

2023-05-15 23:35 UTC, augustnmonteiro commented on frontend/src/App.js
> +import updatedStatus from "./components/updateStatus/update";
remover updatedStatus do App.js pois não está sendo usado nesse arquivo

2023-05-15 23:35 UTC, augustnmonteiro commented on frontend/src/components/updateStatus/update.js
> +    };
trocar o fetch diretamente pelo `Request` dos utilitarios

2023-05-15 23:35 UTC, augustnmonteiro commented on frontend/src/pages/view-packages/ViewPackges.js
> +                {translateStatus(orders.status)}<UpdatedStatus orderId={orders.id} />
no updatedStatus enviar uma função ex:
`<UpdatedStatus orderId={orders.id} onUpdate={loadOrders} />`

2023-05-15 23:35 UTC, augustnmonteiro commented on frontend/src/pages/view-packages/ViewPackges.js
> +    }
usar `switch`

2023-05-15 23:35 UTC, augustnmonteiro commented on frontend/src/components/updateStatus/update.js
> +    }
remover função que atualiza pagina por completo

2023-05-15 23:35 UTC, augustnmonteiro commented on frontend/src/components/updateStatus/update.js
> +function UpdatedStatus({ orderId, currentStatus }) {
receber props com função quando tiver atualização

2023-05-15 23:35 UTC, augustnmonteiro commented on frontend/src/components/updateStatus/update.js
> +    }
chamar a função onUpdate dentro da updateStatus

2023-05-16 13:50 UTC, hugo3az approved these changes

2023-05-17 23:13 UTC, augustnmonteiro requested changes

2023-05-17 23:13 UTC, augustnmonteiro commented on frontend/src/components/updateStatus/update.js
> +            return console.log(data);
não precisa desse return

2023-05-17 23:13 UTC, augustnmonteiro commented on frontend/src/pages/view-packages/ViewPackges.js
> +    }
poderiamos criar um dicionario (objeto)
```js
const statusToText = {
  WAITING_TO_BE_SENT: 'AGUARDANDO ENVIO',
  OUT_FOR_DELIVERY: 'SAIU PARA ENTREGA',
  DELIVERED: 'ENTREGUE'
}

console.log(statusToText[order.status])
```
i18n = internationalization `tradução dos textos`
l10n = localization `ex R$ 10,00 para $ 10.00`

2023-05-18 10:13 UTC, augustnmonteiro approved these changes

2023-05-18 12:03 UTC, DavidFreitas0 approved these changes

2023-05-18 20:42 UTC, Luiz-Honorato approved these changes

2023-05-19 13:31 UTC, merged

2023-05-24 19:30 UTC, ValderlanioJ approved these changes