adicionando componente de pesquisa
augustnmonteiro/gestor-de-encomendas pull request #37
Opened 2023-05-17 22:25 UTC by hugo3az

2023-05-17 23:31 UTC, augustnmonteiro requested changes
excelente trabalho 🚀

2023-05-17 23:31 UTC, augustnmonteiro commented on frontend/src/componenteSearch/componentSearch.js
> +        let search;
remover essa varivael, é uma copia da variavel busca

2023-05-17 23:31 UTC, augustnmonteiro commented on frontend/src/componenteSearch/componentSearch.js
> +            fetch(`http://localhost:3001/orders?type=${type}&busca=${search}`)
usar o Request ao inves do fetch

2023-05-17 23:31 UTC, augustnmonteiro commented on frontend/src/componenteSearch/componentSearch.js
> +        }
alterar somente a variavel `url` e usar o código de fazer a Request somente uma vez

2023-05-17 23:31 UTC, augustnmonteiro commented on frontend/src/componenteSearch/componentSearch.js
> +
```js
function renderInput() {
  if (type === "status") {
     return <select id="status" className="status" value={status} onChange={(e) => buscaStatus(e.target.value)}>
                    <option value=" "></option>
                    <option value="ENTREGUE">ENTREGUE</option>
                    <option value="SAIU PARA ENTREGA">SAIU PARA ENTREGA</option>
                    <option value="AGUARDANDO ENVIO">AGUARDANDO ENVIO</option>
                </select>
  }
  return <input
                    type="search"
                    name="search-form"
                    id="search-form"
                    className="search-input"
                    placeholder="BUSQUE POR UMA ENCOMENDA"
                    onChange={(e) => buscaOrders(e.target.value)}
                />
}
```

2023-05-17 23:31 UTC, augustnmonteiro commented on frontend/src/componenteSearch/componentSearch.js
> +                {!showResults ? <input
```js
{renderInput()}
```

2023-05-17 23:31 UTC, augustnmonteiro commented on frontend/src/context/userContext.js
> +    const [listOrdersComplet, setListOrdersComplet] = React.useState([]);
`listOrdersComplet` e `setListOrdersComplet` não estão sendo usados

2023-05-17 23:34 UTC, augustnmonteiro commented on frontend/src/componenteSearch/componentSearch.js
> +
os values tem que está usando os nomes previamente definidos: `WAITING_TO_BE_SENT, OUT_FOR_DELIVERY , DELIVERED`

2023-05-18 12:04 UTC, DavidFreitas0 approved these changes

2023-05-18 12:23 UTC, augustnmonteiro approved these changes

2023-05-18 12:28 UTC, ivinakarol approved these changes

2023-05-18 20:43 UTC, Luiz-Honorato approved these changes

2023-05-18 21:07 UTC, merged

2023-05-24 19:30 UTC, ValderlanioJ approved these changes