Style form
augustnmonteiro/gestor-de-encomendas pull request #43
Opened 2023-05-24 20:01 UTC by Luiz-Honorato

2023-05-24 22:25 UTC, hugo3az approved these changes

2023-05-24 22:51 UTC, DavidFreitas0 approved these changes

2023-05-24 23:15 UTC, ivinakarol approved these changes

2023-05-24 23:21 UTC, augustnmonteiro requested changes

2023-05-24 23:21 UTC, augustnmonteiro commented on frontend/src/pages/add-order/AddOrder.css
> +.inputForm input, select {
`.inputForm input, .inputForm select`

2023-05-24 23:21 UTC, augustnmonteiro commented on frontend/src/pages/add-order/AddOrder.css
> +.inputForm #status {
temos duas opções.
1. remover a classe ficando somente `#status` 
2. mudar o status de um id para uma classe

2023-05-24 23:23 UTC, augustnmonteiro commented
mergear o `main` aqui dentro, como fazer isso:
1. `git checkout main`
2. `git pull origin main` Atualizar o main local com o main do github
3. `git checkout styleForm` 
4. `git merge main` 
5. `git push origin styleForm`

2023-05-26 20:27 UTC, vanessarlrodrigues approved these changes

2023-05-26 20:28 UTC, vanessarlrodrigues approved these changes

2023-05-26 23:06 UTC, augustnmonteiro approved these changes

2023-05-26 23:17 UTC, merged